'use strict';

const V2_KEY='adc-figueiras-team-manager-v2';
const V1_KEY='adc-figueiras-team-manager-v1';
const MODE_KEY='adc-figueiras-v2-preview-mode';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const pad=n=>String(n).padStart(2,'0');
const uid=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const money=n=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const nowKey=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const fmtDate=iso=>iso?new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(`${iso}T12:00:00`)):'—';
const fmtShort=iso=>iso?new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'short'}).format(new Date(`${iso}T12:00:00`)):'—';
const fmtMonth=d=>new Intl.DateTimeFormat('pt-PT',{month:'long',year:'numeric'}).format(d);
const dateTimeOf=(date,time='23:59')=>new Date(`${date}T${time||'23:59'}:00`);
const initials=n=>String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const addDays=(iso,days)=>{const d=new Date(`${iso}T12:00:00`);d.setDate(d.getDate()+days);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};

const seedPlayers=[
 ['Batista','Jogador'],['David','Jogador'],['Rui Lopes','Jogador'],['João Barros','Jogador'],['Vítor Coelho','Jogador'],
 ['Diogo Bessa','Jogador'],['Pedrinho','Jogador'],['Zé Mocho','Jogador'],['Bruno Bessa','Jogador'],['Joãozinho','Jogador'],
 ['Marcelo','GR'],['João','GR'],['Manu','GR']
].map((p,i)=>({id:`p${i+1}`,name:p[0],position:p[1],number:'',status:'Disponível',birth:'',phone:'',notes:''}));

function defaultState(){
 return {
  schemaVersion:2,
  settings:{club:'ADC Figueiras',activeSeasonId:'s2627',weightReference:'pre',nutritionTemplate:'',nutritionEnabled:false},
  seasons:[{id:'s2627',label:'2026/27',active:true,archived:false}],
  players:seedPlayers.map(p=>({...p})),
  users:[
   {id:'u_david',name:'David',email:'',roles:['player','staff','admin'],playerId:'p2',memberNumber:'',active:true}
  ],
  trainings:[],games:[],fines:[],standings:[],notifications:[],news:[],joinRequests:[]
 };
}

function migrateV1(v1){
 const d=defaultState();
 d.players=(v1.players||d.players).map(p=>({...p}));
 const seasonLabel=v1.settings?.season||'2026/27';
 d.seasons=[{id:'s_migrated',label:seasonLabel,active:true,archived:false}];
 d.settings.activeSeasonId='s_migrated';
 d.settings.club=v1.settings?.club||'ADC Figueiras';
 d.trainings=(v1.trainings||[]).map(t=>({...t,seasonId:'s_migrated'}));
 d.games=(v1.games||[]).map(g=>({...g,seasonId:'s_migrated',status:(g.homeScore!==''&&g.awayScore!=='')?'final':'scheduled',timeline:g.timeline||[]}));
 d.fines=(v1.fines||[]).map(f=>({...f,seasonId:'s_migrated'}));
 const david=d.players.find(p=>p.name.toLowerCase()==='david');
 d.users=[{id:'u_david',name:'David',email:'',roles:['player','staff','admin'],playerId:david?.id||'',memberNumber:'',active:true}];
 d.notifications.push({id:uid('n'),createdAt:new Date().toISOString(),type:'system',title:'V1 migrada para V2',body:'Os dados locais existentes foram importados automaticamente para a nova estrutura.',audience:'admin',status:'sent'});
 return d;
}

function loadState(){
 try{
  const v2=localStorage.getItem(V2_KEY); if(v2) return {...defaultState(),...JSON.parse(v2)};
  const v1=localStorage.getItem(V1_KEY); if(v1){const m=migrateV1(JSON.parse(v1));localStorage.setItem(V2_KEY,JSON.stringify(m));return m;}
 }catch(e){console.warn(e)}
 return defaultState();
}
let state=loadState();
let currentView='dashboard';
let mode=localStorage.getItem(MODE_KEY)||'admin';
let calendarCursor=new Date();calendarCursor.setDate(1);
let toastTimer;

const viewInfo={
 dashboard:['Início','Visão geral do clube'],games:['Jogos','Calendário, resultados e fichas de jogo'],matchcenter:['Match Center','Cronologia e acontecimentos do jogo'],calendar:['Calendário','Treinos e jogos'],standings:['Classificação','Tabela da competição'],stats:['Estatísticas','Jogadores e equipa'],squad:['Plantel','Jogadores e disponibilidade'],training:['Treinos','Presenças e pesagens'],weights:['Pesagens','Histórico e evolução do plantel'],notifications:['Notificações','Comunicação com atletas e sócios'],fines:['Multas','Registo interno'],seasons:['Épocas','Arquivo histórico'],people:['Pessoas e acessos','Utilizadores e múltiplas funções'],settings:['Definições','Dados, backups e integrações']
};

const navDefs=[
 {group:'Clube',items:[['dashboard','⌂','Início'],['games','⚽','Jogos'],['calendar','▦','Calendário'],['standings','🏆','Classificação'],['stats','▥','Estatísticas']]},
 {group:'Equipa',items:[['squad','◉','Plantel'],['training','△','Treinos'],['weights','⚖','Pesagens'],['matchcenter','●','Match Center']]},
 {group:'Comunicação',items:[['notifications','🔔','Notificações']]},
 {group:'Gestão',items:[['fines','€','Multas'],['seasons','↻','Épocas'],['people','♟','Pessoas e acessos'],['settings','⚙','Definições']]}
];
const access={
 public:['dashboard','games','calendar','standings','stats'],
 member:['dashboard','games','calendar','standings','stats','notifications'],
 player:['dashboard','games','calendar','standings','stats','squad','training','weights','matchcenter','notifications'],
 staff:['dashboard','games','calendar','standings','stats','squad','training','weights','matchcenter','notifications','fines'],
 admin:['dashboard','games','calendar','standings','stats','squad','training','weights','matchcenter','notifications','fines','seasons','people','settings']
};
const can=v=>access[mode].includes(v);
const canEdit=()=>mode==='staff'||mode==='admin';
const isAdmin=()=>mode==='admin';

function saveState(msg){localStorage.setItem(V2_KEY,JSON.stringify(state));renderChrome();renderView(currentView);if(msg)toast(msg)}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2200)}
function activeSeason(){return state.seasons.find(s=>s.id===state.settings.activeSeasonId)||state.seasons[0]}
function seasonGames(){return state.games.filter(g=>(g.seasonId||state.settings.activeSeasonId)===state.settings.activeSeasonId)}
function seasonTrainings(){return state.trainings.filter(t=>(t.seasonId||state.settings.activeSeasonId)===state.settings.activeSeasonId)}
function playerById(id){return state.players.find(p=>p.id===id)}
function userByPlayer(id){return state.users.find(u=>u.playerId===id)}
function currentUser(){return state.users.find(u=>u.id==='u_david')||state.users[0]}
function playerHtml(p){return `<div class="player"><div class="avatar">${esc(initials(p.name))}</div><div><strong>${esc(p.name)}</strong><small>${esc(p.position||'Jogador')}${p.number?` · #${esc(p.number)}`:''}</small></div></div>`}
function pill(txt,type='gray'){return `<span class="pill ${type}">${esc(txt)}</span>`}
function empty(t,b=''){return `<div class="empty"><b>${esc(t)}</b>${b?`<span>${esc(b)}</span>`:''}</div>`}
function roleLabel(r){return ({player:'Jogador',staff:'Equipa técnica',admin:'Admin',member:'Sócio'}[r]||r)}
function gameTitle(g){return g.homeAway==='Casa'?`ADC Figueiras vs ${g.opponent}`:`${g.opponent} vs ADC Figueiras`}
function scoreText(g){return (g.homeScore!==''&&g.awayScore!=='')?`${g.homeScore}–${g.awayScore}`:'—'}

function renderChrome(){
 $('#previewMode').value=mode;
 const seasonSel=$('#seasonSelect');seasonSel.innerHTML=state.seasons.filter(s=>!s.archived||s.id===state.settings.activeSeasonId).map(s=>`<option value="${s.id}" ${s.id===state.settings.activeSeasonId?'selected':''}>${esc(s.label)}</option>`).join('');
 const user=currentUser();$('#profileName').textContent=user?.name||'Utilizador';$('#profileRoles').textContent=(user?.roles||[]).map(roleLabel).join(' · ');
 let html='';navDefs.forEach(gr=>{const items=gr.items.filter(i=>can(i[0]));if(!items.length)return;html+=`<div class="nav-group">${gr.group}</div>`+items.map(i=>`<button class="nav-item ${currentView===i[0]?'active':''}" data-view="${i[0]}"><span class="nav-icon">${i[1]}</span>${i[2]}</button>`).join('')});$('#nav').innerHTML=html;
 $$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));
 const unread=state.notifications.filter(n=>!n.read&&notificationVisible(n)).length;$('#notificationCount').textContent=unread;$('#notificationCount').classList.toggle('hidden',!unread);
}
function notificationVisible(n){if(mode==='admin'||mode==='staff')return true;if(mode==='player'){if(n.audience==='player')return n.playerId===currentUser()?.playerId;return ['all','players','roster'].includes(n.audience)}if(mode==='member')return ['all','members'].includes(n.audience);return n.audience==='all'}
function showView(v){if(!can(v)){v='dashboard'}currentView=v;$$('.view').forEach(x=>x.classList.remove('active'));$(`#view-${v}`).classList.add('active');$('#pageTitle').textContent=viewInfo[v][0];$('#pageSubtitle').textContent=viewInfo[v][1];$('#sidebar').classList.remove('open');renderChrome();renderView(v)}
function renderView(v){({dashboard:renderDashboard,games:renderGames,matchcenter:renderMatchCenter,calendar:renderCalendar,standings:renderStandings,stats:renderStats,squad:renderSquad,training:renderTraining,weights:renderWeights,notifications:renderNotifications,fines:renderFines,seasons:renderSeasons,people:renderPeople,settings:renderSettings}[v]||renderDashboard)()}

function playerStats(){
 const out={};state.players.forEach(p=>out[p.id]={games:0,callups:0,goals:0,assists:0,yellow:0,red:0});
 seasonGames().forEach(g=>{
  Object.entries(g.roster||{}).forEach(([id,r])=>{if(!out[id])return;if(r.status==='Convocado'){out[id].callups++;if(g.status==='final'||(g.homeScore!==''&&g.awayScore!==''))out[id].games++;}});
  if((g.timeline||[]).length){g.timeline.forEach(e=>{if(e.playerId&&out[e.playerId]){if(e.type==='goal')out[e.playerId].goals++;if(e.type==='yellow')out[e.playerId].yellow++;if(e.type==='red')out[e.playerId].red++;}if(e.type==='goal'&&e.assistId&&out[e.assistId])out[e.assistId].assists++;});}
  else Object.entries(g.roster||{}).forEach(([id,r])=>{if(!out[id])return;const s=r.stats||{};out[id].goals+=Number(s.goals)||0;out[id].assists+=Number(s.assists)||0;out[id].yellow+=Number(s.yellow)||0;out[id].red+=Number(s.red)||0;});
 });return out;
}
function attendanceRate(){let tot=0,ok=0;seasonTrainings().forEach(t=>state.players.forEach(p=>{const s=t.entries?.[p.id]?.status;if(s){tot++;if(s==='Presente'||s==='Atrasado')ok++;}}));return tot?Math.round(ok/tot*100):0}
function latestWeight(pId){const rows=[];seasonTrainings().forEach(t=>{const e=t.entries?.[pId];if(e?.pre||e?.post)rows.push({date:t.date,pre:Number(e.pre)||null,post:Number(e.post)||null})});rows.sort((a,b)=>b.date.localeCompare(a.date));return rows[0]||null}
function avgWeightLast14(pId,referenceDate){const start=new Date(`${addDays(referenceDate,-14)}T00:00:00`),end=new Date(`${referenceDate}T23:59:59`);const vals=[];state.trainings.forEach(t=>{const d=new Date(`${t.date}T12:00:00`);if(d<start||d>end)return;const e=t.entries?.[pId];if(!e)return;let v=state.settings.weightReference==='post'?Number(e.post):Number(e.pre);if(state.settings.weightReference==='mean'){const a=Number(e.pre),b=Number(e.post);v=(a&&b)?(a+b)/2:(a||b)}if(v>0)vals.push(v)});return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}

function renderDashboard(){
 const games=seasonGames();const now=new Date();const nextGame=[...games].filter(g=>dateTimeOf(g.date,g.time)>=now&&g.status!=='final').sort((a,b)=>dateTimeOf(a.date,a.time)-dateTimeOf(b.date,b.time))[0];const lastGame=[...games].filter(g=>g.status==='final'||(g.homeScore!==''&&g.awayScore!=='')).sort((a,b)=>dateTimeOf(b.date,b.time)-dateTimeOf(a.date,a.time))[0];const nextTraining=[...seasonTrainings()].filter(t=>dateTimeOf(t.date,t.time)>=now).sort((a,b)=>dateTimeOf(a.date,a.time)-dateTimeOf(b.date,b.time))[0];const stats=playerStats();const top=state.players.map(p=>({p,...stats[p.id]})).sort((a,b)=>b.goals-a.goals||b.assists-a.assists).slice(0,5);const notices=state.notifications.filter(notificationVisible).slice(-4).reverse();
 const hero=nextGame?`<div class="card hero"><div class="eyebrow">Próximo jogo · ${esc(nextGame.competition||'Competição')}</div><div class="club-vs"><div class="crest"><img src="assets/adc-figueiras-emblema.png"></div><div><h2>${esc(gameTitle(nextGame))}</h2><div class="muted">${fmtDate(nextGame.date)} · ${esc(nextGame.time||'Hora por definir')}${nextGame.venue?` · ${esc(nextGame.venue)}`:''}</div></div></div><div class="hero-actions"><button class="btn secondary" data-open-game="${nextGame.id}">Abrir Match Center</button>${canEdit()?`<button class="btn secondary" data-notify-gameday="${nextGame.id}">Preparar “DIA DE JOGO!”</button>`:''}</div></div>`:`<div class="card hero"><div class="eyebrow">Época ${esc(activeSeason()?.label||'')}</div><h2>ADC Figueiras</h2><p class="muted">Ainda não existe próximo jogo registado.</p>${canEdit()?'<div class="hero-actions"><button class="btn secondary" id="dashAddGame">Adicionar jogo</button></div>':''}</div>`;
 const joinBlock=mode==='public'?`<div style="height:15px"></div><div class="card"><div class="card-head"><div><h3>Fazer parte do Figueiras</h3><p>Atletas e sócios poderão aderir à plataforma com a sua própria conta.</p></div><button class="btn" id="joinClub">Aderir</button></div></div>`:'';$('#view-dashboard').innerHTML=`${hero}${joinBlock}<div style="height:15px"></div><div class="grid kpis"><div class="card kpi"><div class="label">Jogos</div><div class="value">${games.length}</div><div class="sub">na época ativa</div></div><div class="card kpi"><div class="label">Golos marcados</div><div class="value">${games.reduce((s,g)=>s+(Number(g.homeScore)||0),0)}</div><div class="sub">registados</div></div><div class="card kpi"><div class="label">${mode==='public'||mode==='member'?'Jogos concluídos':'Assiduidade'}</div><div class="value">${mode==='public'||mode==='member'?games.filter(g=>g.status==='final'||(g.homeScore!==''&&g.awayScore!=='')).length:attendanceRate()+(String.fromCharCode(37))}</div><div class="sub">${mode==='public'||mode==='member'?'resultados publicados':'treinos com registo'}</div></div><div class="card kpi"><div class="label">Plantel</div><div class="value">${state.players.length}</div><div class="sub">jogadores</div></div></div><div style="height:15px"></div><div class="grid two"><div class="card"><div class="card-head"><div><h3>Atualidade</h3><p>Treino e último resultado</p></div></div>${(mode==='player'||canEdit())?`<div class="list-row"><div><strong>Próximo treino</strong><div class="meta">${nextTraining?`${fmtDate(nextTraining.date)} · ${nextTraining.time||'—'}${nextTraining.location?` · ${esc(nextTraining.location)}`:''}`:'Sem treino agendado'}</div></div>${nextTraining?pill('Treino','green'):''}</div>`:''}<div class="list-row"><div><strong>Último resultado</strong><div class="meta">${lastGame?`${esc(gameTitle(lastGame))} · ${fmtDate(lastGame.date)}`:'Sem resultados registados'}</div></div>${lastGame?`<span class="score">${scoreText(lastGame)}</span>`:''}</div><div class="card-head" style="margin-top:16px"><div><h3>Melhores marcadores</h3><p>Época ${esc(activeSeason()?.label||'')}</p></div></div>${top.some(x=>x.goals||x.assists)?`<div class="list">${top.map((x,i)=>`<div class="list-row"><div>${playerHtml(x.p)}</div><div><strong>${x.goals}</strong> G · ${x.assists} A</div></div>`).join('')}</div>`:empty('Sem estatísticas','Os golos e assistências surgem ao registar os jogos.')}</div><div class="card"><div class="card-head"><div><h3>Notificações</h3><p>Comunicação preparada para atletas e sócios</p></div>${can('notifications')?'<button class="btn secondary sm" id="goNotifications">Ver todas</button>':''}</div>${notices.length?notices.map(noticeHtml).join(''):empty('Sem notificações','As notificações de jogo, convocatória e resultado aparecerão aqui.')}</div></div>`;
 $$('[data-open-game]').forEach(b=>b.onclick=()=>{sessionStorage.setItem('mcGame',b.dataset.openGame);showView('matchcenter')});
 $$('[data-notify-gameday]').forEach(b=>b.onclick=()=>prepareGameDayNotification(b.dataset.notifyGameday));
 $('#dashAddGame')&&($('#dashAddGame').onclick=openGameCreate);$('#goNotifications')&&($('#goNotifications').onclick=()=>showView('notifications'));$('#joinClub')&&($('#joinClub').onclick=openJoinRequest);
}

function openJoinRequest(){openModal('Aderir ao ADC Figueiras','Pedido de acesso à futura plataforma online.',`<form id="joinForm"><div class="form-grid"><div class="field"><label>Nome</label><input name="name" required></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field full"><label>Quero aderir como</label><select name="kind"><option value="member">Sócio</option><option value="player">Atleta</option></select></div></div><div class="form-actions"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn">Enviar pedido</button></div></form>`);$('#joinForm').onsubmit=e=>{e.preventDefault();state.joinRequests=state.joinRequests||[];state.joinRequests.push({id:uid('jr'),...Object.fromEntries(new FormData(e.target)),createdAt:new Date().toISOString(),status:'pending'});closeModal();saveState('Pedido registado nesta preview. Na versão online seguirá para a administração.')};$('[data-close]').onclick=closeModal}

function renderGames(){const rows=[...seasonGames()].sort((a,b)=>dateTimeOf(a.date,a.time)-dateTimeOf(b.date,b.time));$('#view-games').innerHTML=`<div class="section-head"><div><h2>Jogos · ${esc(activeSeason()?.label||'')}</h2><p>Todos os compromissos da época.</p></div>${canEdit()?'<button class="btn" id="addGame">＋ Novo jogo</button>':''}</div>${rows.length?rows.map(g=>`<div class="game-card"><div class="when"><strong>${fmtShort(g.date).split(' ')[0]}</strong><small>${fmtShort(g.date).split(' ').slice(1).join(' ')}</small></div><div class="main-info"><h4>${esc(gameTitle(g))}</h4><p>${esc(g.competition||'Jogo')} · ${esc(g.time||'Hora por definir')}${g.venue?` · ${esc(g.venue)}`:''}</p></div><div>${g.status==='final'?`<span class="score">${scoreText(g)}</span>`:pill(g.status==='live'?'AO VIVO':'Agendado',g.status==='live'?'red':'blue')}</div><div class="inline-actions"><button class="btn secondary sm open-game" data-id="${g.id}">Match Center</button>${canEdit()?`<button class="btn secondary sm edit-game" data-id="${g.id}">Editar</button>`:''}</div></div>`).join(''):empty('Ainda não existem jogos','Adiciona o calendário da época para começar.')}`;$('#addGame')&&($('#addGame').onclick=openGameCreate);$$('.open-game').forEach(b=>b.onclick=()=>{sessionStorage.setItem('mcGame',b.dataset.id);showView('matchcenter')});$$('.edit-game').forEach(b=>b.onclick=()=>openGameManage(b.dataset.id))}

function openGameCreate(){openModal('Novo jogo','Adiciona o jogo à época ativa.',`<form id="gameForm"><div class="form-grid"><div class="field"><label>Data *</label><input type="date" name="date" value="${nowKey()}" required></div><div class="field"><label>Hora</label><input type="time" name="time"></div><div class="field full"><label>Adversário *</label><input name="opponent" required></div><div class="field"><label>Casa / Fora</label><select name="homeAway"><option>Casa</option><option>Fora</option></select></div><div class="field"><label>Competição</label><input name="competition" placeholder="Campeonato / Taça / Amigável"></div><div class="field full"><label>Pavilhão / local</label><input name="venue"></div></div><div class="form-actions"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn">Criar jogo</button></div></form>`);$('#gameForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const roster={};state.players.forEach(p=>roster[p.id]={status:'Não convocado',stats:{goals:0,assists:0,yellow:0,red:0}});const g={id:uid('g'),seasonId:state.settings.activeSeasonId,...d,status:'scheduled',homeScore:'',awayScore:'',roster,timeline:[]};state.games.push(g);closeModal();saveState();sessionStorage.setItem('mcGame',g.id);showView('matchcenter')};$('[data-close]').onclick=closeModal}

function openGameManage(id){const g=state.games.find(x=>x.id===id);if(!g)return;g.roster=g.roster||{};const roster=state.players.map(p=>{const r=g.roster[p.id]||{status:'Não convocado'};return `<div class="list-row" data-rp="${p.id}"><div>${playerHtml(p)}</div><select class="roster-status"><option ${r.status==='Convocado'?'selected':''}>Convocado</option><option ${r.status==='Não convocado'?'selected':''}>Não convocado</option><option ${r.status==='Lesionado'?'selected':''}>Lesionado</option><option ${r.status==='Castigado'?'selected':''}>Castigado</option></select></div>`}).join('');openModal(gameTitle(g),`${fmtDate(g.date)} · ${esc(g.competition||'Jogo')}`,`<div class="form-grid"><div class="field"><label>Data</label><input id="gDate" type="date" value="${esc(g.date)}"></div><div class="field"><label>Hora</label><input id="gTime" type="time" value="${esc(g.time||'')}"></div><div class="field"><label>Golos Figueiras</label><input id="gHome" type="number" min="0" value="${esc(g.homeScore)}"></div><div class="field"><label>Golos adversário</label><input id="gAway" type="number" min="0" value="${esc(g.awayScore)}"></div><div class="field"><label>Estado</label><select id="gStatus"><option value="scheduled" ${g.status==='scheduled'?'selected':''}>Agendado</option><option value="live" ${g.status==='live'?'selected':''}>Ao vivo</option><option value="final" ${g.status==='final'?'selected':''}>Final</option></select></div><div class="field"><label>Local</label><input id="gVenue" value="${esc(g.venue||'')}"></div></div><div class="card-head" style="margin-top:18px"><div><h3>Convocatória</h3><p>Seleciona os jogadores convocados.</p></div><button class="btn secondary sm" id="allCalled">Convocar todos</button></div><div class="list">${roster}</div><div class="form-actions"><button class="btn danger" id="deleteGame">Eliminar</button><span style="flex:1"></span><button class="btn secondary" data-close>Fechar</button><button class="btn" id="saveGame">Guardar</button></div>`,true);$('#allCalled').onclick=()=>$$('.roster-status').forEach(s=>s.value='Convocado');$('#saveGame').onclick=()=>{g.date=$('#gDate').value;g.time=$('#gTime').value;g.homeScore=$('#gHome').value;g.awayScore=$('#gAway').value;g.status=$('#gStatus').value;g.venue=$('#gVenue').value;$$('[data-rp]').forEach(r=>{g.roster[r.dataset.rp]=g.roster[r.dataset.rp]||{stats:{}};g.roster[r.dataset.rp].status=$('.roster-status',r).value});closeModal();saveState('Jogo atualizado.')};$('#deleteGame').onclick=()=>{if(confirm('Eliminar este jogo?')){state.games=state.games.filter(x=>x.id!==g.id);closeModal();saveState('Jogo eliminado.')}};$('[data-close]').onclick=closeModal}

function renderMatchCenter(){let id=sessionStorage.getItem('mcGame');let g=state.games.find(x=>x.id===id);if(!g){g=[...seasonGames()].sort((a,b)=>Math.abs(dateTimeOf(a.date,a.time)-new Date())-Math.abs(dateTimeOf(b.date,b.time)-new Date()))[0]}if(!g){$('#view-matchcenter').innerHTML=empty('Sem jogos','Cria um jogo para abrir o Match Center.');return}sessionStorage.setItem('mcGame',g.id);const events=[...(g.timeline||[])].sort((a,b)=>(Number(a.minute)||999)-(Number(b.minute)||999));const called=Object.entries(g.roster||{}).filter(([,r])=>r.status==='Convocado').map(([id])=>playerById(id)).filter(Boolean);$('#view-matchcenter').innerHTML=`<div class="section-head"><div><h2>Match Center</h2><p>${fmtDate(g.date)} · ${esc(g.competition||'Jogo')}</p></div><div class="inline-actions">${canEdit()?`<button class="btn secondary" id="editThisGame">Convocatória / resultado</button><button class="btn" id="addEvent">＋ Acontecimento</button>`:''}</div></div><div class="match-grid"><div class="card match-scoreboard"><div class="eyebrow">${g.status==='live'?'AO VIVO':g.status==='final'?'FINAL':'PRÓXIMO JOGO'}</div><div class="teams"><div class="team-name">${g.homeAway==='Casa'?'ADC Figueiras':esc(g.opponent)}</div><div class="big-score">${scoreText(g)}</div><div class="team-name">${g.homeAway==='Casa'?esc(g.opponent):'ADC Figueiras'}</div></div><div class="muted">${esc(g.time||'Hora por definir')} · ${esc(g.venue||'Local por definir')}</div><div class="hero-actions" style="justify-content:center">${canEdit()?`<button class="btn blue sm" id="notifGameDay">DIA DE JOGO!</button><button class="btn secondary sm" id="notifCallup">Convocatória</button><button class="btn amber sm" id="notifFood">Plano pré-jogo</button>${g.status==='final'?'<button class="btn danger sm" id="notifFinal">Resultado final</button>':''}`:''}</div><div class="card-head" style="margin-top:20px;text-align:left"><div><h3>Convocados</h3><p>${called.length} jogador(es)</p></div></div>${called.length?`<div class="tags">${called.map(p=>pill(p.name,'green')).join('')}</div>`:empty('Convocatória por definir')}</div><div class="card"><div class="card-head"><div><h3>Cronologia</h3><p>Golos, assistências e cartões alimentam as estatísticas.</p></div></div>${events.length?`<div class="timeline">${events.map(eventHtml).join('')}</div>`:empty('Ainda sem acontecimentos','A cronologia começa quando registares eventos do jogo.')}</div></div>`;$('#editThisGame')&&($('#editThisGame').onclick=()=>openGameManage(g.id));$('#addEvent')&&($('#addEvent').onclick=()=>openEventCreate(g.id));$('#notifGameDay')&&($('#notifGameDay').onclick=()=>prepareGameDayNotification(g.id));$('#notifCallup')&&($('#notifCallup').onclick=()=>prepareCallupNotification(g.id));$('#notifFood')&&($('#notifFood').onclick=()=>prepareNutritionNotifications(g.id));$('#notifFinal')&&($('#notifFinal').onclick=()=>prepareFinalNotification(g.id))}
function eventHtml(e){const cls=e.type==='yellow'?'cardy':e.type==='red'?'cardr':e.type==='note'?'note':'goal';const p=playerById(e.playerId);const a=playerById(e.assistId);const label={goal:'⚽ Golo',yellow:'🟨 Cartão amarelo',red:'🟥 Cartão vermelho',halftime:'Intervalo',note:'Nota'}[e.type]||e.type;return `<div class="timeline-event ${cls}"><div class="timeline-dot"></div><div><span class="minute">${e.minute?`${esc(e.minute)}'`:''}</span> <strong>${label}${p?` · ${esc(p.name)}`:''}</strong>${a?`<small>Assistência: ${esc(a.name)}</small>`:''}${e.text?`<small>${esc(e.text)}</small>`:''}</div></div>`}
function openEventCreate(gameId){const g=state.games.find(x=>x.id===gameId);const opts=state.players.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');openModal('Novo acontecimento',gameTitle(g),`<form id="eventForm"><div class="form-grid"><div class="field"><label>Tipo</label><select name="type"><option value="goal">Golo</option><option value="yellow">Cartão amarelo</option><option value="red">Cartão vermelho</option><option value="halftime">Intervalo</option><option value="note">Nota</option></select></div><div class="field"><label>Minuto</label><input name="minute" type="number" min="0" max="60"></div><div class="field"><label>Jogador</label><select name="playerId"><option value="">—</option>${opts}</select></div><div class="field"><label>Assistência</label><select name="assistId"><option value="">—</option>${opts}</select></div><div class="field full"><label>Nota</label><input name="text" placeholder="Opcional"></div></div><div class="form-actions"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn">Adicionar</button></div></form>`);$('#eventForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));g.timeline=g.timeline||[];g.timeline.push({id:uid('ev'),...d});closeModal();saveState('Acontecimento adicionado.');renderMatchCenter()};$('[data-close]').onclick=closeModal}

function createNotification({type,title,body,audience='all',gameId='',playerId='',trigger='manual',scheduledDate=''}){const n={id:uid('n'),createdAt:new Date().toISOString(),type,title,body,audience,gameId,playerId,trigger,scheduledDate,status:'prepared',read:false};state.notifications.push(n);return n}
function prepareGameDayNotification(id){const g=state.games.find(x=>x.id===id);if(!g)return;createNotification({type:'game',title:'DIA DE JOGO!',body:`${gameTitle(g)} · ${fmtDate(g.date)}${g.time?` às ${g.time}`:''}${g.venue?` · ${g.venue}`:''}`,audience:'all',gameId:g.id,trigger:'game_day',scheduledDate:g.date});saveState('Notificação “DIA DE JOGO!” preparada.')}
function prepareCallupNotification(id){const g=state.games.find(x=>x.id===id);if(!g)return;const ids=Object.entries(g.roster||{}).filter(([,r])=>r.status==='Convocado').map(([id])=>id);if(!ids.length){toast('Ainda não há jogadores convocados.');return}ids.forEach(pid=>createNotification({type:'callup',title:'CONVOCATÓRIA',body:`Estás convocado para ${gameTitle(g)} · ${fmtDate(g.date)}${g.time?` · ${g.time}`:''}.`,audience:'player',gameId:g.id,playerId:pid,trigger:'callup'}));saveState(`Convocatória preparada para ${ids.length} jogador(es).`)}
function prepareFinalNotification(id){const g=state.games.find(x=>x.id===id);if(!g)return;createNotification({type:'final',title:'RESULTADO FINAL',body:`${gameTitle(g)} · ${scoreText(g)}`,audience:'all',gameId:g.id,trigger:'final'});saveState('Notificação de resultado final preparada.')}
function renderNutritionTemplate(template,avg,p,g){return String(template||'').replaceAll('{{peso_medio}}',avg?avg.toFixed(1):'—').replaceAll('{{jogador}}',p?.name||'Jogador').replaceAll('{{adversario}}',g?.opponent||'').replaceAll('{{hora_jogo}}',g?.time||'').replaceAll('{{data_jogo}}',fmtDate(g?.date))}
function prepareNutritionNotifications(id){const g=state.games.find(x=>x.id===id);if(!g)return;const ids=Object.entries(g.roster||{}).filter(([,r])=>r.status==='Convocado').map(([id])=>id);if(!ids.length){toast('Ainda não há jogadores convocados.');return}const day=addDays(g.date,-1);ids.forEach(pid=>{const avg=avgWeightLast14(pid,g.date);const p=playerById(pid);let body=`Jogo amanhã: ${gameTitle(g)}. `;body+=avg?`Peso médio das últimas 2 semanas: ${avg.toFixed(1)} kg. `:'Sem pesagens suficientes nas últimas 2 semanas. ';if(state.settings.nutritionEnabled&&state.settings.nutritionTemplate&&avg){body+=renderNutritionTemplate(state.settings.nutritionTemplate,avg,p,g)}else body+='Plano alimentar ainda por configurar pela equipa técnica.';createNotification({type:'food',title:'PLANO PRÉ-JOGO',body,audience:'player',gameId:g.id,playerId:pid,trigger:'day_before_game',scheduledDate:day})});saveState(`Plano pré-jogo preparado para ${ids.length} convocado(s).`)}
function noticeHtml(n){return `<div class="notice-card ${esc(n.type)}"><h4>${esc(n.title)}</h4><p>${esc(n.body)}</p><div class="notice-meta"><span>${n.scheduledDate?`Programada: ${fmtDate(n.scheduledDate)}`:new Date(n.createdAt).toLocaleString('pt-PT')}</span><span>${esc(n.audience==='all'?'Jogadores + sócios':n.audience==='players'?'Jogadores':n.audience==='members'?'Sócios':n.audience==='player'?'Jogador':'Interno')}</span></div></div>`}

function renderNotifications(){const rows=state.notifications.filter(notificationVisible).slice().reverse();$('#view-notifications').innerHTML=`<div class="section-head"><div><h2>Notificações</h2><p>Convocatórias, dia de jogo, resultados e plano pré-jogo.</p></div><div class="inline-actions"><button class="btn secondary" id="enableBrowserNotifications">Ativar no dispositivo</button>${canEdit()?'<button class="btn" id="customNotification">＋ Nova</button>':''}</div></div><div class="warning-strip">Nesta preview, as notificações ficam preparadas dentro da app e podes testar notificações imediatas do browser. O envio push agendado com a app fechada será ligado quando ativarmos o backend.</div><div style="height:12px"></div><div class="grid equal2">${rows.length?rows.map(noticeHtml).join(''):empty('Sem notificações','Ainda não existem mensagens preparadas.')}</div>`;$('#enableBrowserNotifications').onclick=requestNotificationPermission;$('#customNotification')&&($('#customNotification').onclick=openCustomNotification);state.notifications.forEach(n=>{if(notificationVisible(n))n.read=true});localStorage.setItem(V2_KEY,JSON.stringify(state));renderChrome()}
async function requestNotificationPermission(){if(!('Notification'in window)){toast('Este browser não suporta notificações.');return}const p=await Notification.requestPermission();if(p==='granted'){new Notification('ADC Figueiras',{body:'Notificações ativadas neste dispositivo.',icon:'assets/icon-192.png'});toast('Notificações ativadas.')}else toast('Permissão não concedida.')}
function openCustomNotification(){openModal('Nova notificação','Mensagem manual para a comunidade.',`<form id="notifForm"><div class="form-grid"><div class="field full"><label>Título</label><input name="title" required></div><div class="field full"><label>Mensagem</label><textarea name="body" required></textarea></div><div class="field"><label>Destinatários</label><select name="audience"><option value="all">Jogadores + sócios</option><option value="players">Jogadores</option><option value="members">Sócios</option></select></div></div><div class="form-actions"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn">Preparar</button></div></form>`);$('#notifForm').onsubmit=e=>{e.preventDefault();createNotification({...Object.fromEntries(new FormData(e.target)),type:'system'});closeModal();saveState('Notificação preparada.')};$('[data-close]').onclick=closeModal}

function renderTraining(){const rows=[...seasonTrainings()].sort((a,b)=>dateTimeOf(b.date,b.time)-dateTimeOf(a.date,a.time));$('#view-training').innerHTML=`<div class="section-head"><div><h2>Treinos</h2><p>Presenças registadas pela equipa técnica. Os atletas não precisam confirmar nem justificar na app.</p></div>${canEdit()?'<button class="btn" id="addTraining">＋ Novo treino</button>':''}</div>${rows.length?`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Local</th><th>Presenças</th><th>Pesagens</th><th></th></tr></thead><tbody>${rows.map(t=>{const entries=Object.values(t.entries||{});const pres=entries.filter(e=>e.status==='Presente'||e.status==='Atrasado').length;const ws=entries.filter(e=>e.pre||e.post).length;return `<tr><td><strong>${fmtDate(t.date)}</strong><div class="meta">${esc(t.time||'')}</div></td><td>${esc(t.location||'—')}</td><td>${pres}/${state.players.length}</td><td>${ws}</td><td><div class="inline-actions"><button class="btn secondary sm open-training" data-id="${t.id}">${canEdit()?'Gerir':'Ver'}</button>${canEdit()?`<button class="btn danger sm delete-training" data-id="${t.id}">Eliminar</button>`:''}</div></td></tr>`}).join('')}</tbody></table></div>`:empty('Ainda não existem treinos','Cria o primeiro treino da época.')}`;$('#addTraining')&&($('#addTraining').onclick=openTrainingCreate);$$('.open-training').forEach(b=>b.onclick=()=>openTrainingManage(b.dataset.id));$$('.delete-training').forEach(b=>b.onclick=()=>{if(confirm('Eliminar este treino?')){state.trainings=state.trainings.filter(t=>t.id!==b.dataset.id);saveState('Treino eliminado.')}})}
function openTrainingCreate(){openModal('Novo treino','Sessão de treino da época ativa.',`<form id="trainingForm"><div class="form-grid"><div class="field"><label>Data *</label><input type="date" name="date" value="${nowKey()}" required></div><div class="field"><label>Hora</label><input type="time" name="time" value="21:30"></div><div class="field full"><label>Local</label><input name="location"></div><div class="field full"><label>Notas internas</label><textarea name="notes"></textarea></div></div><div class="form-actions"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn">Criar treino</button></div></form>`);$('#trainingForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const t={id:uid('t'),seasonId:state.settings.activeSeasonId,...d,entries:{}};state.trainings.push(t);closeModal();saveState();openTrainingManage(t.id)};$('[data-close]').onclick=closeModal}
function openTrainingManage(id){const t=state.trainings.find(x=>x.id===id);if(!t)return;const editable=canEdit();const rows=state.players.map(p=>{const e=t.entries?.[p.id]||{};const a=Number(e.pre),b=Number(e.post),delta=a&&b?b-a:null,pct=a&&b?(b-a)/a*100:null;return `<div class="training-row" data-player="${p.id}">${playerHtml(p)}<select class="att-status" ${editable?'':'disabled'}><option value="">— Estado —</option>${['Presente','Atrasado','Falta','Lesionado'].map(s=>`<option ${e.status===s?'selected':''}>${s}</option>`).join('')}</select><input class="w-pre" type="number" step="0.1" min="0" placeholder="Antes kg" value="${esc(e.pre||'')}" ${editable?'':'disabled'}><input class="w-post" type="number" step="0.1" min="0" placeholder="Depois kg" value="${esc(e.post||'')}" ${editable?'':'disabled'}><div class="delta">${delta===null?'—':`${delta>0?'+':''}${delta.toFixed(1)} kg<br><span class="muted">${pct.toFixed(2)}%</span>`}</div></div>`}).join('');openModal(`Treino · ${fmtDate(t.date)}`,`${t.time||''}${t.location?` · ${t.location}`:''}`,`${editable?'<div class="info-strip">A equipa técnica regista presenças e pesos. Não existe confirmação/justificação pelo atleta.</div><div style="height:10px"></div>':''}<div class="training-roster">${rows}</div><div class="form-actions"><button class="btn secondary" data-close>Fechar</button>${editable?'<button class="btn" id="saveTraining">Guardar</button>':''}</div>`,true);$('#saveTraining')&&($('#saveTraining').onclick=()=>{t.entries=t.entries||{};$$('.training-row',$('#modalBody')).forEach(r=>{t.entries[r.dataset.player]={status:$('.att-status',r).value,pre:$('.w-pre',r).value,post:$('.w-post',r).value}});closeModal();saveState('Treino atualizado.')});$('[data-close]').onclick=closeModal}

function renderWeights(){const ref=state.settings.weightReference;const cards=state.players.map(p=>{const l=latestWeight(p.id);const avg=avgWeightLast14(p.id,nowKey());return `<div class="weight-card"><div>${playerHtml(p)}</div><div><div class="weight-label">Último pré</div><div class="weight-number">${l?.pre?`${l.pre.toFixed(1)} kg`:'—'}</div></div><div><div class="weight-label">Último pós</div><div class="weight-number">${l?.post?`${l.post.toFixed(1)} kg`:'—'}</div></div><div><div class="weight-label">Média 2 semanas</div><div class="weight-number">${avg?`${avg.toFixed(1)} kg`:'—'}</div></div></div>`}).join('');$('#view-weights').innerHTML=`<div class="section-head"><div><h2>Pesagens do plantel</h2><p>Os atletas podem consultar as próprias pesagens e as dos colegas.</p></div>${canEdit()?`<span class="pill blue">Referência plano: ${ref==='pre'?'pré-treino':ref==='post'?'pós-treino':'média pré/pós'}</span>`:''}</div><div class="warning-strip">A visibilidade das pesagens está configurada de acordo com a decisão atual do clube. Antes de abrir a plataforma a todos, convém definir formalmente a política de acesso a estes dados.</div><div style="height:12px"></div><div class="grid">${cards||empty('Sem jogadores')}</div>`}

function renderSquad(){const stats=playerStats();$('#view-squad').innerHTML=`<div class="section-head"><div><h2>Plantel</h2><p>Plantel e estatísticas da época.</p></div>${canEdit()?'<button class="btn" id="addPlayer">＋ Jogador</button>':''}</div><div class="table-wrap"><table><thead><tr><th>Jogador</th><th>Estado</th><th>Jogos</th><th>Golos</th><th>Assist.</th><th></th></tr></thead><tbody>${state.players.map(p=>`<tr><td>${playerHtml(p)}</td><td>${pill(p.status||'Disponível',p.status==='Disponível'?'green':p.status==='Lesionado'?'red':'amber')}</td><td>${stats[p.id].games}</td><td>${stats[p.id].goals}</td><td>${stats[p.id].assists}</td><td>${canEdit()?`<button class="btn secondary sm edit-player" data-id="${p.id}">Editar</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;$('#addPlayer')&&($('#addPlayer').onclick=()=>openPlayer());$$('.edit-player').forEach(b=>b.onclick=()=>openPlayer(b.dataset.id))}
function openPlayer(id=''){const p=id?playerById(id):{id:'',name:'',position:'Jogador',number:'',status:'Disponível'};openModal(id?'Editar jogador':'Novo jogador','Dados básicos do plantel.',`<form id="playerForm"><div class="form-grid"><div class="field full"><label>Nome *</label><input name="name" value="${esc(p.name)}" required></div><div class="field"><label>Posição</label><select name="position"><option ${p.position==='Jogador'?'selected':''}>Jogador</option><option ${p.position==='GR'?'selected':''}>GR</option></select></div><div class="field"><label>Número</label><input name="number" value="${esc(p.number||'')}"></div><div class="field"><label>Estado</label><select name="status">${['Disponível','Lesionado','Castigado','Indisponível'].map(x=>`<option ${p.status===x?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="form-actions"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn">Guardar</button></div></form>`);$('#playerForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(id)Object.assign(p,d);else state.players.push({id:uid('p'),...d});closeModal();saveState('Plantel atualizado.')};$('[data-close]').onclick=closeModal}

function renderStats(){const stats=playerStats();const rows=state.players.map(p=>({p,...stats[p.id]})).sort((a,b)=>b.goals-a.goals||b.assists-a.assists);const games=seasonGames().filter(g=>g.status==='final'||(g.homeScore!==''&&g.awayScore!==''));let w=0,d=0,l=0,gf=0,ga=0;games.forEach(g=>{const a=Number(g.homeScore)||0,b=Number(g.awayScore)||0;gf+=a;ga+=b;if(a>b)w++;else if(a===b)d++;else l++});$('#view-stats').innerHTML=`<div class="grid kpis"><div class="card kpi"><div class="label">Jogos concluídos</div><div class="value">${games.length}</div></div><div class="card kpi"><div class="label">V / E / D</div><div class="value">${w}/${d}/${l}</div></div><div class="card kpi"><div class="label">Golos</div><div class="value">${gf}</div><div class="sub">marcados</div></div><div class="card kpi"><div class="label">Diferença</div><div class="value">${gf-ga>0?'+':''}${gf-ga}</div></div></div><div style="height:15px"></div><div class="card"><div class="card-head"><div><h3>Estatísticas individuais</h3><p>Dados da época ${esc(activeSeason()?.label||'')}</p></div></div><div class="table-wrap"><table><thead><tr><th>Jogador</th><th>Conv.</th><th>Jogos</th><th>Golos</th><th>Assist.</th><th>G+A</th><th>🟨</th><th>🟥</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${playerHtml(x.p)}</td><td>${x.callups}</td><td>${x.games}</td><td>${x.goals}</td><td>${x.assists}</td><td><strong>${x.goals+x.assists}</strong></td><td>${x.yellow}</td><td>${x.red}</td></tr>`).join('')}</tbody></table></div></div>`}

function renderStandings(){let st=state.standings.find(x=>x.seasonId===state.settings.activeSeasonId);if(!st){st={id:uid('st'),seasonId:state.settings.activeSeasonId,competition:'',rows:[]};state.standings.push(st)}const sorted=[...st.rows].sort((a,b)=>Number(b.pts)-Number(a.pts)||(Number(b.gf)-Number(b.ga))-(Number(a.gf)-Number(a.ga)));$('#view-standings').innerHTML=`<div class="section-head"><div><h2>Classificação</h2><p>${esc(st.competition||'Competição por definir')} · ${esc(activeSeason()?.label||'')}</p></div>${canEdit()?'<div class="inline-actions"><button class="btn secondary" id="editCompetition">Competição</button><button class="btn" id="addStandingRow">＋ Equipa</button></div>':''}</div>${sorted.length?`<div class="table-wrap"><table><thead><tr><th>#</th><th>Equipa</th><th>J</th><th>V</th><th>E</th><th>D</th><th>GM</th><th>GS</th><th>DG</th><th>Pts</th><th></th></tr></thead><tbody>${sorted.map((r,i)=>`<tr class="${String(r.team).toLowerCase().includes('figueiras')?'highlight-row':''}"><td>${i+1}</td><td><strong>${esc(r.team)}</strong></td><td>${r.j||0}</td><td>${r.v||0}</td><td>${r.e||0}</td><td>${r.d||0}</td><td>${r.gf||0}</td><td>${r.ga||0}</td><td>${(Number(r.gf)||0)-(Number(r.ga)||0)}</td><td><strong>${r.pts||0}</strong></td><td>${canEdit()?`<button class="btn secondary sm edit-standing" data-id="${r.id}">Editar</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:empty('Classificação ainda não introduzida','Nesta fase pode ser preenchida manualmente; mais tarde podemos estudar importação automática.')}`;$('#editCompetition')&&($('#editCompetition').onclick=()=>{const x=prompt('Nome da competição:',st.competition||'');if(x!==null){st.competition=x;saveState()}});$('#addStandingRow')&&($('#addStandingRow').onclick=()=>openStandingRow(st));$$('.edit-standing').forEach(b=>b.onclick=()=>openStandingRow(st,b.dataset.id))}
function openStandingRow(st,id=''){const r=id?st.rows.find(x=>x.id===id):{team:'',j:0,v:0,e:0,d:0,gf:0,ga:0,pts:0};openModal(id?'Editar classificação':'Adicionar equipa','Valores da tabela classificativa.',`<form id="standingForm"><div class="form-grid"><div class="field full"><label>Equipa</label><input name="team" value="${esc(r.team)}" required></div>${[['j','J'],['v','V'],['e','E'],['d','D'],['gf','GM'],['ga','GS'],['pts','Pts']].map(([k,l])=>`<div class="field"><label>${l}</label><input name="${k}" type="number" min="0" value="${Number(r[k])||0}"></div>`).join('')}</div><div class="form-actions">${id?'<button type="button" class="btn danger" id="delStanding">Eliminar</button>':''}<span style="flex:1"></span><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn">Guardar</button></div></form>`);$('#standingForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(id)Object.assign(r,d);else st.rows.push({id:uid('sr'),...d});closeModal();saveState()};$('#delStanding')&&($('#delStanding').onclick=()=>{st.rows=st.rows.filter(x=>x.id!==id);closeModal();saveState()});$('[data-close]').onclick=closeModal}

function renderCalendar(){const first=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth(),1),start=new Date(first);start.setDate(1-((first.getDay()+6)%7));const events=[...seasonTrainings().map(t=>({date:t.date,type:'training',label:`Treino ${t.time||''}`})),...seasonGames().map(g=>({date:g.date,type:'game',label:`${g.homeAway==='Casa'?'vs':'@'} ${g.opponent}`}))];let days='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;const muted=d.getMonth()!==calendarCursor.getMonth();days+=`<div class="calendar-day ${muted?'muted':''} ${k===nowKey()?'today':''}"><div class="day-num">${d.getDate()}</div>${events.filter(e=>e.date===k).map(e=>`<span class="cal-event ${e.type==='game'?'game':''}">${esc(e.label)}</span>`).join('')}</div>`}$('#view-calendar').innerHTML=`<div class="calendar-head"><button class="btn secondary sm" id="prevMonth">←</button><h2>${fmtMonth(calendarCursor)}</h2><button class="btn secondary sm" id="nextMonth">→</button></div><div class="calendar-grid">${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(x=>`<div class="dow">${x}</div>`).join('')}${days}</div>`;$('#prevMonth').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()}}

function renderFines(){const rows=state.fines.filter(f=>(f.seasonId||state.settings.activeSeasonId)===state.settings.activeSeasonId);const pending=rows.filter(f=>!f.paid).reduce((s,f)=>s+Number(f.amount||0),0);$('#view-fines').innerHTML=`<div class="section-head"><div><h2>Multas</h2><p>Gestão interna da equipa.</p></div><button class="btn" id="addFine">＋ Multa</button></div><div class="grid kpis"><div class="card kpi"><div class="label">Pendentes</div><div class="value">${money(pending)}</div></div><div class="card kpi"><div class="label">Registos</div><div class="value">${rows.length}</div></div></div><div style="height:15px"></div>${rows.length?`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Jogador</th><th>Motivo</th><th>Valor</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(f=>`<tr><td>${fmtDate(f.date)}</td><td>${esc(playerById(f.playerId)?.name||'—')}</td><td>${esc(f.reason||'')}</td><td>${money(f.amount)}</td><td>${pill(f.paid?'Pago':'Pendente',f.paid?'green':'red')}</td><td><button class="btn secondary sm toggle-fine" data-id="${f.id}">${f.paid?'Marcar pendente':'Marcar pago'}</button></td></tr>`).join('')}</tbody></table></div>`:empty('Sem multas registadas')}`;$('#addFine').onclick=openFine;$$('.toggle-fine').forEach(b=>b.onclick=()=>{const f=state.fines.find(x=>x.id===b.dataset.id);f.paid=!f.paid;saveState()})}
function openFine(){const opts=state.players.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');openModal('Nova multa','Registo interno.',`<form id="fineForm"><div class="form-grid"><div class="field"><label>Jogador</label><select name="playerId">${opts}</select></div><div class="field"><label>Data</label><input type="date" name="date" value="${nowKey()}"></div><div class="field full"><label>Motivo</label><input name="reason" required></div><div class="field"><label>Valor (€)</label><input type="number" step="0.01" min="0" name="amount" required></div></div><div class="form-actions"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn">Guardar</button></div></form>`);$('#fineForm').onsubmit=e=>{e.preventDefault();state.fines.push({id:uid('f'),seasonId:state.settings.activeSeasonId,...Object.fromEntries(new FormData(e.target)),paid:false});closeModal();saveState('Multa registada.')};$('[data-close]').onclick=closeModal}

function renderSeasons(){$('#view-seasons').innerHTML=`<div class="section-head"><div><h2>Épocas</h2><p>Arquivo de jogos, treinos e estatísticas.</p></div><button class="btn" id="addSeason">＋ Nova época</button></div><div class="grid equal2">${state.seasons.map(s=>`<div class="card"><div class="card-head"><div><h3>${esc(s.label)}</h3><p>${state.games.filter(g=>g.seasonId===s.id).length} jogos · ${state.trainings.filter(t=>t.seasonId===s.id).length} treinos</p></div>${s.id===state.settings.activeSeasonId?pill('Ativa','green'):pill(s.archived?'Arquivo':'Disponível','gray')}</div><div class="inline-actions"><button class="btn secondary sm set-season" data-id="${s.id}">Abrir época</button>${s.id!==state.settings.activeSeasonId?`<button class="btn secondary sm archive-season" data-id="${s.id}">${s.archived?'Reativar':'Arquivar'}</button>`:''}</div></div>`).join('')}</div>`;$('#addSeason').onclick=()=>{const label=prompt('Ex.: 2025/26');if(!label)return;const s={id:uid('s'),label,active:false,archived:false};state.seasons.push(s);saveState('Época criada.')};$$('.set-season').forEach(b=>b.onclick=()=>{state.settings.activeSeasonId=b.dataset.id;saveState();showView('dashboard')});$$('.archive-season').forEach(b=>b.onclick=()=>{const s=state.seasons.find(x=>x.id===b.dataset.id);s.archived=!s.archived;saveState()})}

function renderPeople(){const roles=['player','staff','admin','member'];$('#view-people').innerHTML=`<div class="section-head"><div><h2>Pessoas e acessos</h2><p>Uma pessoa pode acumular várias funções na mesma conta.</p></div><button class="btn" id="addUser">＋ Pessoa</button></div><div class="info-strip">Exemplo: a conta do David pode ter simultaneamente Jogador + Equipa técnica + Admin. As permissões acumulam-se, não é necessário criar contas separadas.</div><div style="height:12px"></div><div class="table-wrap"><table><thead><tr><th>Pessoa</th><th>Funções</th><th>Jogador associado</th><th>Sócio nº</th><th></th></tr></thead><tbody>${state.users.map(u=>`<tr><td><strong>${esc(u.name)}</strong><div class="meta">${esc(u.email||'Sem email')}</div></td><td><div class="tags">${u.roles.map(r=>pill(roleLabel(r),r==='admin'?'purple':r==='staff'?'blue':r==='player'?'green':'amber')).join('')}</div></td><td>${esc(playerById(u.playerId)?.name||'—')}</td><td>${esc(u.memberNumber||'—')}</td><td><button class="btn secondary sm edit-user" data-id="${u.id}">Editar</button></td></tr>`).join('')}</tbody></table></div>`;$('#addUser').onclick=()=>openUser();$$('.edit-user').forEach(b=>b.onclick=()=>openUser(b.dataset.id))}
function openUser(id=''){const u=id?state.users.find(x=>x.id===id):{name:'',email:'',roles:[],playerId:'',memberNumber:'',active:true};const po=state.players.map(p=>`<option value="${p.id}" ${u.playerId===p.id?'selected':''}>${esc(p.name)}</option>`).join('');openModal(id?'Editar pessoa':'Nova pessoa','Funções acumuláveis na mesma conta.',`<form id="userForm"><div class="form-grid"><div class="field"><label>Nome</label><input name="name" value="${esc(u.name)}" required></div><div class="field"><label>Email</label><input type="email" name="email" value="${esc(u.email||'')}"></div><div class="field"><label>Jogador associado</label><select name="playerId"><option value="">— Nenhum —</option>${po}</select></div><div class="field"><label>N.º sócio</label><input name="memberNumber" value="${esc(u.memberNumber||'')}"></div><div class="field full"><label>Funções</label><div class="checkboxes">${['player','staff','admin','member'].map(r=>`<label class="check-pill"><input type="checkbox" name="roles" value="${r}" ${u.roles.includes(r)?'checked':''}>${roleLabel(r)}</label>`).join('')}</div></div></div><div class="form-actions"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn">Guardar</button></div></form>`);$('#userForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);const data={name:fd.get('name'),email:fd.get('email'),playerId:fd.get('playerId'),memberNumber:fd.get('memberNumber'),roles:fd.getAll('roles'),active:true};if(id)Object.assign(u,data);else state.users.push({id:uid('u'),...data});closeModal();saveState('Acessos atualizados.')};$('[data-close]').onclick=closeModal}

function renderSettings(){$('#view-settings').innerHTML=`<div class="settings-stack"><div class="card"><div class="card-head"><div><h3>Plano alimentar pré-jogo</h3><p>Base para a notificação enviada aos convocados na véspera.</p></div>${pill(state.settings.nutritionEnabled?'Ativo':'A aguardar plano',state.settings.nutritionEnabled?'green':'amber')}</div><div class="form-grid"><div class="field"><label>Peso de referência</label><select id="weightReference"><option value="pre" ${state.settings.weightReference==='pre'?'selected':''}>Peso pré-treino</option><option value="post" ${state.settings.weightReference==='post'?'selected':''}>Peso pós-treino</option><option value="mean" ${state.settings.weightReference==='mean'?'selected':''}>Média pré/pós</option></select></div><div class="field full"><label>Template do plano alimentar</label><textarea id="nutritionTemplate" placeholder="Mais tarde colocamos aqui o plano que vais fornecer. Variáveis disponíveis: {{peso_medio}}, {{jogador}}, {{adversario}}, {{data_jogo}}, {{hora_jogo}}.">${esc(state.settings.nutritionTemplate||'')}</textarea></div></div><div class="form-actions"><button class="btn" id="saveNutrition">Guardar configuração</button></div></div><div class="card"><div class="card-head"><div><h3>Backups</h3><p>Protege os dados locais antes de atualizações.</p></div></div><div class="inline-actions"><button class="btn secondary" id="exportData">Exportar JSON</button><button class="btn secondary" id="importData">Importar JSON</button></div></div><div class="card"><div class="card-head"><div><h3>Backend / sincronização</h3><p>Fundação preparada para contas reais, vários dispositivos e push.</p></div></div><div class="warning-strip">Esta build ainda funciona localmente. Login real, sincronização entre utilizadores e notificações push agendadas exigem ligar uma base de dados/backend. O pacote inclui um esquema SQL de referência para essa fase.</div></div><div class="card danger-zone"><div class="card-head"><div><h3>Dados locais</h3><p>Operação irreversível sem backup.</p></div></div><button class="btn danger" id="resetData">Repor V2</button></div></div>`;$('#saveNutrition').onclick=()=>{state.settings.weightReference=$('#weightReference').value;state.settings.nutritionTemplate=$('#nutritionTemplate').value.trim();state.settings.nutritionEnabled=!!state.settings.nutritionTemplate;saveState('Configuração guardada.')};$('#exportData').onclick=exportData;$('#importData').onclick=()=>$('#importInput').click();$('#resetData').onclick=()=>{if(confirm('Apagar os dados da V2 neste dispositivo?')){state=defaultState();saveState('Dados repostos.')}}}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`adc-figueiras-backup-${nowKey()}.json`;a.click();URL.revokeObjectURL(a.href)}

function openModal(title,subtitle,html,wide=false){$('#modalTitle').textContent=title;$('#modalSubtitle').textContent=subtitle||'';$('#modalBody').innerHTML=html;$('#modal').classList.toggle('wide',!!wide);$('#modalBackdrop').classList.remove('hidden')}
function closeModal(){$('#modalBackdrop').classList.add('hidden')}

$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#closeModal').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))closeModal()};$('#previewMode').onchange=e=>{mode=e.target.value;localStorage.setItem(MODE_KEY,mode);if(!can(currentView))currentView='dashboard';renderChrome();showView(currentView)};$('#seasonSelect').onchange=e=>{state.settings.activeSeasonId=e.target.value;saveState();showView('dashboard')};$('#notificationBell').onclick=()=>showView('notifications');$('#importInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data.schemaVersion)throw new Error('Formato inválido');state={...defaultState(),...data};saveState('Backup importado.')}catch(err){alert('Não foi possível importar este ficheiro.')}};r.readAsText(file);e.target.value=''};
window.addEventListener('online',()=>$('#offlineBanner').classList.add('hidden'));window.addEventListener('offline',()=>$('#offlineBanner').classList.remove('hidden'));if(!navigator.onLine)$('#offlineBanner').classList.remove('hidden');
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});

renderChrome();showView('dashboard');
